apiVersion: v1
kind: Service
metadata:
  name: clairsvc
  namespace: registry-system
  labels:
    app: clair
spec:
  type: NodePort
  ports:
  - port: 6060
    protocol: TCP
    nodePort: 30060
    name: clair-port0
  - port: 6061
    protocol: TCP
    nodePort: 30061
    name: clair-port1
  selector:
    app: clair
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: clair
  namespace: registry-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: clair
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: clairsecret
      - name: registry-secret
        secret:
          secretName: registry-ca
      containers:
      - name: clair
        image: quay.io/coreos/clair
        args:
          - "-config"
          - "/config/config.yaml"
        # - "-insecure-tls"
        ports:
        - containerPort: 6060
        - containerPort: 6061
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                update-ca-certificates
        volumeMounts:
        - mountPath: /config
          name: secret-volume
        - mountPath: /usr/local/share/ca-certificates
          name: registry-secret
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: postgres
  name: clair-postgres
  namespace: registry-system
spec:
  replicas: 1
  selector:
    app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:latest
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
          name: postgres-port
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: registry-system
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
