apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry-system
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
      delete:
        enabled: true
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    notifications:
      endpoints:
      - name: registry-operator
        url: http://registry-operator-service.registry-system:28677/registry/event