apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: registry-system
data:
  manager_config.yaml: |
    # cluster:
      # name: my-kube
    # image:
      # registry: <image_registry>
      # registry_pull_secret: <registry-pull-secret>
    registry:
      image: registry:2.7.1
      image_pull_secret: ""
    notary:
      server:
        image: tmaxcloudck/notary_server:0.6.2-rc1
        image_pull_secret: ""
      signer:
        image: tmaxcloudck/notary_signer:0.6.2-rc1
        image_pull_secret: ""
      db:
        image: tmaxcloudck/notary_mysql:0.6.2-rc1
        image_pull_secret: ""
    keycloak:
      service: https://172.22.11.9:8443
    scanning:
      scanner:
        url: "http://clair.registry-system.svc.cluster.local:6060"
        insecure: false
      report:
        url: "http://elasticsearch.kube-logging.svc.cluster.local:9200"
    harbor:
      namespace: harbor
      core:
        ingress: tmax-harbor-ingress
      notary:
        ingress: tmax-harbor-ingress-notary
    external_registry:
      sync_period: "*/5 * * * *"