apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-operator
  namespace: registry-system
  labels:
    control-plane: registry-operator
spec:
  selector:
    matchLabels:
      control-plane: registry-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: registry-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: tmaxcloudck/registry-operator:v0.3.5
        name: manager
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "registry-operator"
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: Asia/Seoul
          - name: KEYCLOAK_USERNAME
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: username
          - name: KEYCLOAK_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: operator-log-mnt
          mountPath: /var/log/registry-operator
        - name: registry-secret
          mountPath: /etc/ssl/certs/ca.crt
          subPath: ca.crt
        - name: manager-config
          mountPath: /registry-operator/config
      volumes:
      - name: operator-log-mnt
        hostPath:
          path: /var/log/registry-operator/logs/registry-operator
      - name: registry-secret
        secret:
          secretName: registry-ca
      - name: manager-config
        configMap:
          name: manager-config
      terminationGracePeriodSeconds: 10
