apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-operator
  namespace: registry-system
  labels:
    control-plane: registry-operator
spec:
  selector:
    matchLabels:
      control-plane: registry-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: registry-operator
    spec:
      containers:
      - command:
        - /bin/dev/manager
        args:
        - --enable-leader-election
        image: tmaxcloudck/registry-operator:0.0.1-dev
        name: manager
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: "registry-operator"
          - name: TZ
            value: Asia/Seoul
          - name: KEYCLOAK_SERVICE
            value: https://172.22.11.9:8443
          - name: KEYCLOAK_USERNAME
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: username
          - name: KEYCLOAK_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
          - name: CLAIR_URL
            value: "http://clairsvc.default.svc.cluster.local:6060"
          - name: WEBHOOK_URL
            value: "http://elasticsearch-svc.default.svc.cluster.local:9200"
#        resources:
#          limits:
#            cpu: 100m
#            memory: 30Mi
#          requests:
#            cpu: 100m
#            memory: 20Mi
        volumeMounts:
        - name: manager-mnt
          mountPath: /bin/dev
        - name: operator-log-mnt
          mountPath: /logs    
      volumes:
      - name: manager-mnt
        hostPath:
          path: "/root/go/src/github.com/tmax-cloud/registry-operator/bin"
      - name: operator-log-mnt
        hostPath:
          path: "/root/go/src/github.com/tmax-cloud/registry-operator/logs"
      nodeSelector:
        kubernetes.io/hostname: node1
      terminationGracePeriodSeconds: 10
