apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-operator
  namespace: registry-system
  labels:
    control-plane: registry-operator
spec:
  selector:
    matchLabels:
      control-plane: registry-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: registry-operator
    spec:
      containers:
      - command:
        - /bin/dev/manager
        args:
        - --enable-leader-election
        image: tmaxcloudck/registry-operator:0.0.1-dev
        name: manager
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: "registry-operator"
          - name: TZ
            value: Asia/Seoul
          # CLUSTER_NAME is Name for distinguishing clusters
          # If registry resource is created with CLUSTER_NAME set, you must delete all of the resources and change this value
          # - name: CLUSTER_NAME
          #  value: {CLUSTER_NAME}
          # IMAGE_REGISTRY is private image registry url including image such as registry:2.7.1 and tmaxcloudck/notary_server:0.6.2-rc1 etc. 
          # Input like 172.22.11.2:5000 at <image_registry>.
          # - name: IMAGE_REGISTRY
          #   value: "<image_registry>"
          # - name: IMAGE_REGISTRY_PULL_SECRET
          #   value: "<registry-pull-secret>"
          - name: KEYCLOAK_SERVICE
            value: https://172.22.11.9:8443
          - name: KEYCLOAK_USERNAME
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: username
          - name: KEYCLOAK_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
          - name: CLAIR_URL
            value: "http://clairsvc.default.svc.cluster.local:6060"
          - name: ELASTIC_SEARCH_URL
            value: "http://elasticsearch-svc.default.svc.cluster.local:9200"
#        resources:
#          limits:
#            cpu: 100m
#            memory: 30Mi
#          requests:
#            cpu: 100m
#            memory: 20Mi
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/sbin/update-ca-certificates
        volumeMounts:
        - name: manager-mnt
          mountPath: /bin/dev
        - name: operator-log-mnt
          mountPath: /logs
        - name: registry-secret
          mountPath: /usr/local/share/ca-certificates/ca.crt
          subPath: ca.crt
        - name: extra-ca-secret
          mountPath: /usr/local/share/ca-certificates/extra-ca.crt
          subPath: extra-ca.crt
      volumes:
      - name: manager-mnt
        hostPath:
          path: "/root/go/src/github.com/tmax-cloud/registry-operator/bin"
      - name: operator-log-mnt
        hostPath:
          path: "/root/go/src/github.com/tmax-cloud/registry-operator/logs"
      - name: registry-secret
        secret:
          secretName: registry-ca
      - name: extra-ca-secret
        secret:
          secretName: extra-ca
      nodeSelector:
        kubernetes.io/hostname: node1
      terminationGracePeriodSeconds: 10
