apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-operator
  namespace: registry-system
  labels:
    control-plane: registry-operator
spec:
  selector:
    matchLabels:
      control-plane: registry-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: registry-operator
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: tmaxcloudck/registry-operator:{REGISTRY_OPERATOR_VERSION}
        name: manager
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "registry-operator"
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TZ
            value: Asia/Seoul
          # CLUSTER_NAME is Name for distinguishing clusters
          # If registry resource is created with CLUSTER_NAME set, you must delete all of the resources and change this value
          # - name: CLUSTER_NAME
          #   value: {CLUSTER_NAME}
          # IMAGE_REGISTRY is private image registry url including image such as registry:2.7.1 and tmaxcloudck/notary_server:0.6.2-rc1 etc. 
          # Input like 172.22.11.2:5000 at <image_registry>.
          # - name: IMAGE_REGISTRY
          #   value: "<image_registry>"
          # - name: IMAGE_REGISTRY_PULL_SECRET
          #   value: "<registry-pull-secret>"
          - name: KEYCLOAK_SERVICE
            value: https://keycloak-test-service.reg-test.svc.cluster.local:8443
          - name: KEYCLOAK_USERNAME
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: username
          - name: KEYCLOAK_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: password
          - name: CLAIR_URL
            value: "http://clairsvc.default.svc.cluster.local:6060"
          - name: ELASTIC_SEARCH_URL
            value: "http://elasticsearch-svc.default.svc.cluster.local:9200"
          - name: HARBOR_NAMESPACE
            value: harbor
          - name: HARBOR_CORE_INGRESS
            value: tmax-harbor-ingress
          - name: HARBOR_NOTARY_INGRESS
            value: tmax-harbor-ingress-notary
#        resources:
#          limits:
#            cpu: 100m
#            memory: 30Mi
#          requests:
#            cpu: 100m
#            memory: 20Mi
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/sbin/update-ca-certificates
        volumeMounts:
        - name: operator-log-mnt
          mountPath: /logs
        - mountPath: /usr/local/share/ca-certificates
          name: registry-secret  
      volumes:
      - name: operator-log-mnt
        hostPath:
          path: {LOG_FILE_PATH}
      - name: registry-secret
        secret:
          secretName: registry-ca
      terminationGracePeriodSeconds: 10
