# Source: opendistro-es/templates/elasticsearch/es-data-svc.yaml
# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
apiVersion: v1
kind: Service
metadata:
  labels:
    app: efk-opendistro-es
    chart: "opendistro-es-1.12.0"
    release: "efk"
    heritage: "Helm"
    role: data
  name: efk-opendistro-es-data-svc
  namespace: efk
spec:
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  - port: 9600
    name: metrics
  - port: 9650
    name: rca
  clusterIP: None
  selector:
    role: data
---
# Source: opendistro-es/templates/elasticsearch/es-service.yaml
# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
kind: Service
apiVersion: v1
metadata:
  annotations:
    {}
  labels:
    app: efk-opendistro-es
    chart: "opendistro-es-1.12.0"
    release: "efk"
    heritage: "Helm"
    role: client
  name: efk-opendistro-es-client-service
  namespace: efk
spec:
  ports:
    - name: http
      port: 9200
    - name: transport
      port: 9300
    - name: metrics
      port: 9600
    - name: rca
      port: 9650
  selector:
    role: client
  type: NodePort
---
# Source: opendistro-es/templates/elasticsearch/master-svc.yaml
# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
apiVersion: v1
kind: Service
metadata:
  labels:
    app: efk-opendistro-es
    chart: "opendistro-es-1.12.0"
    release: "efk"
    heritage: "Helm"
    role: master
  name: efk-opendistro-es-discovery
  namespace: efk
spec:
  ports:
    - port: 9300
      protocol: TCP
  clusterIP: None
  selector:
    role: master