
# @formatter:off
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: efk-opendistro-es
    chart: "opendistro-es-1.12.0"
    release: "efk"
    heritage: "Helm"
    role: client
  name: efk-opendistro-es-client
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efk-opendistro-es
      release: "efk"
      heritage: "Helm"
      role: client
  template:
    metadata:
      labels:
        app: efk-opendistro-es
        chart: "opendistro-es-1.12.0"
        release: "efk"
        heritage: "Helm"
        role: client
      annotations:
        
    spec:      
      serviceAccountName: efk-opendistro-es-es
      initContainers:
      - name: init-sysctl
        image: docker.io/busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        command:
        - /bin/bash
        - -c
        - |
          sed -i 's/anonymous_auth_enabled\: false/anonymous_auth_enabled\: true/g' /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
          echo ${EMAIL_USER} | sh ./bin/elasticsearch-keystore add --stdin --force opendistro.alerting.destination.email.notification.username
          echo ${EMAIL_PASSWORD} | sh ./bin/elasticsearch-keystore add --stdin --force opendistro.alerting.destination.email.notification.password
          /usr/local/bin/docker-entrypoint.sh eswrapper
        securityContext:
          capabilities:
            add: ["SYS_CHROOT"]
        env:
        - name: cluster.name
          value: elasticsearch
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "true"
        - name: node.data
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: efk-opendistro-es-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: EMAIL_USER
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: EMAIL_PASSWORD
        
        resources:
            {}
        # Official Image from Open Distro Team
        image: docker.io/amazon/opendistro-for-elasticsearch:1.12.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        - containerPort: 9600
          name: metrics
        - containerPort: 9650
          name: rca
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      volumes:
      - name: config
        secret:
          secretName: efk-opendistro-es-es-config
---
# Source: opendistro-es/templates/elasticsearch/es-data-sts.yaml
# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: efk-opendistro-es
    chart: "opendistro-es-1.12.0"
    release: "efk"
    heritage: "Helm"
    role: data
  name: efk-opendistro-es-data
  namespace: efk
spec:
  serviceName: efk-opendistro-es-data-svc
  replicas: 1
  selector:
    matchLabels:
      app: efk-opendistro-es
      release: "efk"
      heritage: "Helm"
      role: data
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: efk-opendistro-es
        chart: "opendistro-es-1.12.0"
        release: "efk"
        heritage: "Helm"
        role: data
      annotations:
        
    spec:      
      initContainers:
      - name: init-sysctl
        image: docker.io/busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fixmount
        command: [ 'sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data' ]
        image: docker.io/busybox:1.27.2
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: 
      serviceAccountName: efk-opendistro-es-es
      containers:
      - name: elasticsearch
        command:
        - /bin/bash
        - -c
        - |
          sed -i 's/anonymous_auth_enabled\: false/anonymous_auth_enabled\: true/g' /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
          echo ${EMAIL_USER} | sh ./bin/elasticsearch-keystore add --stdin --force opendistro.alerting.destination.email.notification.username
          echo ${EMAIL_PASSWORD} | sh ./bin/elasticsearch-keystore add --stdin --force opendistro.alerting.destination.email.notification.password
          /usr/local/bin/docker-entrypoint.sh eswrapper
        securityContext:
          capabilities:
            add: ["SYS_CHROOT"]
        env:
        - name: cluster.name
          value: elasticsearch
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "efk-opendistro-es-discovery"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.data
          value: "true"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: EMAIL_USER
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: EMAIL_PASSWORD
        # Official Image from Open Distro Team
        image: docker.io/amazon/opendistro-for-elasticsearch:1.12.0
        imagePullPolicy: "Always"
        # only publish the transport port
        ports:
        - containerPort: 9300
          name: transport
        resources:
            {}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: 
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      volumes:
      - name: config
        secret:
          secretName: efk-opendistro-es-es-config
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: csi-cephfs-sc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-cephfs-sc
      resources:
        requests:
          storage: "8Gi"
---
# Source: opendistro-es/templates/elasticsearch/es-master-sts.yaml
# Copyright 2019 Viasat, Inc.
# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

# @formatter:off
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: efk-opendistro-es
    chart: "opendistro-es-1.12.0"
    release: "efk"
    heritage: "Helm"
    role: master
  name: efk-opendistro-es-master
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efk-opendistro-es
      release: "efk"
      heritage: "Helm"
      role: master
  updateStrategy:
    type: RollingUpdate
  serviceName: efk-opendistro-es-discovery
  template:
    metadata:
      labels:
        app: efk-opendistro-es
        chart: "opendistro-es-1.12.0"
        release: "efk"
        heritage: "Helm"
        role: master
    spec:      
      serviceAccountName: efk-opendistro-es-es
      initContainers:
      - name: init-sysctl
        image: docker.io/busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      - name: fixmount
        command: [ 'sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data' ]
        image: docker.io/busybox:1.27.2
        volumeMounts:
          - mountPath: /usr/share/elasticsearch/data
            name: data
            subPath: 
      containers:
      - name: elasticsearch
        command:
        - /bin/bash
        - -c
        - |
          sed -i 's/anonymous_auth_enabled\: false/anonymous_auth_enabled\: true/g' /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
          echo ${EMAIL_USER} | sh ./bin/elasticsearch-keystore add --stdin --force opendistro.alerting.destination.email.notification.username
          echo ${EMAIL_PASSWORD} | sh ./bin/elasticsearch-keystore add --stdin --force opendistro.alerting.destination.email.notification.password
          /usr/local/bin/docker-entrypoint.sh eswrapper
        securityContext:
          capabilities:
            add: ["SYS_CHROOT"]
        env:
        - name: cluster.name
          value: elasticsearch
        - name: cluster.initial_master_nodes
          value: efk-opendistro-es-master-0,
        - name: node.master
          value: "true"
        - name: node.ingest
          value: "false"
        - name: node.data
          value: "false"
        - name: network.host
          value: "0.0.0.0"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: efk-opendistro-es-discovery
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: EMAIL_USER
        - name: EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: EMAIL_PASSWORD
      
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: transport
        # Official Image from Open Distro Team
        image: docker.io/amazon/opendistro-for-elasticsearch:1.12.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        - containerPort: 9600
          name: metrics
        - containerPort: 9650
          name: rca
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: data
          subPath: 
        - mountPath: /usr/share/elasticsearch/config/logging.yml
          name: config
          subPath: logging.yml
      volumes:
      - name: config
        secret:
          secretName: efk-opendistro-es-es-logging
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: csi-cephfs-sc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csi-cephfs-sc
      resources:
        requests:
          storage: "8Gi"