apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: registry-crds-r-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  resourceNames:
  - imagescanrequests.tmax.io
  - imagesigners.tmax.io
  - imagesignrequests.tmax.io
  - notaries.tmax.io
  - registries.tmax.io
  - repositories.tmax.io
  - signerkeys.tmax.io
  - signerpolicies.tmax.io
  verbs:
  - get
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: registry-all-rw-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagescanrequests
  - imagesigners
  - imagesignrequests
  - notaries
  - registries
  - repositories
  - signerkeys
  - signerpolicies
  verbs:
  - "*"
