# permissions for end users to edit externalregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalregistry-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - externalregistries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - externalregistries/status
  verbs:
  - get
