# permissions for end users to view imagescanrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagescanrequest-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagescanrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagescanrequests/status
  verbs:
  - get
