# permissions for end users to view imagereplicates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagereplicate-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagereplicates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagereplicates/status
  verbs:
  - get
