# permissions for end users to edit imagescanrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagescanrequest-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagescanrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagescanrequests/status
  verbs:
  - get
