# permissions for end users to edit imagereplicates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagereplicate-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - imagereplicates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - imagereplicates/status
  verbs:
  - get
