# permissions for end users to edit notaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notary-editor-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - notaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tmax.io
  resources:
  - notaries/status
  verbs:
  - get
