# permissions for end users to view notaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: notary-viewer-role
rules:
- apiGroups:
  - tmax.io
  resources:
  - notaries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tmax.io
  resources:
  - notaries/status
  verbs:
  - get
