apiVersion: v1
kind: Namespace
metadata:
  name: registry-system

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: registry-system-quota
  namespace: registry-system
spec:
  hard:
    limits.cpu: "4"
    limits.memory: "20Gi"
    requests.storage: "30Gi"