apiVersion: v1
kind: Service
metadata:
  name: hypercloud4-operator-service
  namespace: hypercloud4-system
spec:
  ports:
  - name: "port1"
    port: 28677
    protocol: TCP
    targetPort: 28677
  selector:
    hypercloud4: operator
  type: LoadBalancer