apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud-operator-go
  namespace: hypercloud4-system
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud4: operator
  template:
    metadata:
      labels:
        hypercloud4: operator
    spec:
      serviceAccountName: hypercloud4-admin
      containers:
        - name: hypercloud-operator-go
          image: dlwlsdnjsehs/registry-operator:v0.0.1
          command:
          - hypercloud-operator-go
          imagePullPolicy: Always
          volumeMounts:
          - name: hypercloud4-mnt
            mountPath: /usr/local/bin
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hypercloud-operator-go"
            - name: TZ
              value: Asia/Seoul
          ports:
          - containerPort: 28677
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"