apiVersion: apps/v1
kind: Deployment
metadata:
  name: hypercloud-operator-go
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hypercloud-operator-go
  template:
    metadata:
      labels:
        name: hypercloud-operator-go
    spec:
      serviceAccountName: hypercloud-operator-go
      containers:
        - name: hypercloud-operator-go
          # Replace this with the built image name
          image: dlwlsdnjsehs/registry-operator:v0.0.1 
          command:
          - hypercloud-operator-go
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hypercloud-operator-go"
