apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-operator
  namespace: registry-system
spec:
  replicas: 1
  selector:
    matchLabels:
      hypercloud4: operator
  template:
    metadata:
      labels:
        hypercloud4: operator
    spec:
      serviceAccountName: hypercloud4-admin
      containers:
        - name: registry-operator
          image: docker.io/tmaxcloudck/registry-operator:nightly
          command:
          - registry-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "registry-operator"
            - name: TZ
              value: Asia/Seoul
          ports:
          - containerPort: 28677
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"