apiVersion: tmax.io/v1
kind: Registry
metadata:
  name: tmax-registry
  namespace: reg-test 
spec:
  image: registry:2.6.2
  description: test
  loginId: tmax
  loginPassword: tmax123
  notary:
    enabled: true
    serviceType: Ingress
    persistentVolumeClaim:
      create:
        accessModes: [ReadWriteOnce]
        storageSize: 10Gi
        storageClassName: csi-cephfs-sc
        deleteWithPvc: true
  service:
    serviceType: Ingress 
  persistentVolumeClaim:
    mountPath: /var/lib/registry
    #exist:
      #pvcName: hpcd-tmax3-registry
    create:
      accessModes: [ReadWriteOnce]
      storageSize: 10Gi
      storageClassName: csi-cephfs-sc
      deleteWithPvc: true
