apiVersion: v1
kind: Pod
metadata:
  name: tmax-pod
  namespace: reg-test
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: <Registry>/tomcat:8.5
    imagePullPolicy: Always
    resources:
      limits:
        cpu: "200m"
        memory: "1Gi"
  nodeSelector:
    kubernetes.io/hostname: <host_name>
  imagePullSecrets:
  - name: hpcd-registry-tmp-tmax-registry