apiVersion: tmax.io/v1
kind: Registry
metadata:
  name: tmax-registry
  namespace: reg-test
spec:
  image: registry:2.6.2
  description: test
  loginId: tmax
  loginPassword: tmax123
  notary:
    enabled: true
    serviceType: LoadBalancer
    persistentVolumeClaim:
      create:
        accessModes: [ReadWriteOnce]
        storageSize: 10Gi
        storageClassName: csi-cephfs-sc
        volumeMode: Filesystem
        deleteWithPvc: true
  service:
    serviceType: LoadBalancer
    loadBalancer:
      port: 443
  persistentVolumeClaim:
    mountPath: /var/lib/registry
    create:
      accessModes: [ReadWriteOnce]
      storageSize: 10Gi
      storageClassName: csi-cephfs-sc
      volumeMode: Filesystem
      deleteWithPvc: true
