apiVersion: tmax.io/v1
kind: Registry
metadata:
  name: tmax-registry
  namespace: reg-test
spec:
  image: registry:2.7.1
  description: test
  loginId: tmax
  loginPassword: tmax123
  registryDeployment:
    #labels:
    #  test: labeltest
    #nodeSelector:
    #  kubernetes.io/hostname: node1
    #selector:
    #  test: labeltest
    #tolerations:
    #- effect: NoSchedule
    #  key: node-role.kubernetes.io/master
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 100m
        memory: 512Mi
  notary:
    enabled: false
    serviceType: LoadBalancer
    persistentVolumeClaim:
      create:
        accessModes: [ReadWriteOnce]
        storageSize: 10Gi
        storageClassName: csi-cephfs-sc
        deleteWithPvc: true
  service:
    serviceType: LoadBalancer
  persistentVolumeClaim:
    mountPath: /var/lib/registry
    create:
      accessModes: [ReadWriteOnce]
      storageSize: 10Gi
      storageClassName: csi-cephfs-sc
      deleteWithPvc: true
