apiVersion: tmax.io/v1
kind: RegistryCronJob
metadata:
  name: rcj-sync-harbor-1
spec:
  schedule: "*/5 * * * *"
  jobSpec:
    ttl: -1
    priority: 0
    claim:
      jobType: Synchronize
      handleObject:
        name: harbor-1
