apiVersion: tmax.io/v1
kind: Notary
metadata:
  name: notary-sample
  namespace: reg-test
spec:
  # Add fields here
  rootCASecret: hpcd-registry-rootca
  authConfig:
    realm: https://172.22.11.9:8443/auth/realms/reg-test-tmax-registry/protocol/docker-v2/auth
    service: reg-test-tmax-registry-docker-client
    issuer: https://172.22.11.9:8443/auth/realms/reg-test-tmax-registry
  serviceType: LoadBalancer
  persistentVolumeClaim:
    create:
      accessModes: [ReadWriteMany]
      storageSize: 10Gi
      storageClassName: csi-cephfs-sc
      deleteWithPvc: true
