apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.tmax.io
  annotations:
    operator.version: 4.1.0.37
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: registries
    singular: registry
    kind: Registry
    shortNames:
      - reg
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      required: [spec]
      properties:
        operatorStartTime:
          type: string
        spec:
          type: object
          oneOf:
            - required: [image, loginId, loginPassword, service, persistentVolumeClaim]
          description: registry information // [CHECK]
          properties:
            image:
              type: string
            description:
              type: string
            loginId:
              type: string
            loginPassword:
              type: string
            customConfigYml:
              type: string
              description: "The name of the configmap where the registry config.yml content"    // [CHECK]
            replicaSet:
              type: object
              properties:
                labels:
                  type: object
                  additionalProperties:
                    type: string
                nodeSelector:
                  type: object
                  description: node selector
                  additionalProperties:
                    type: string
                selector:
                  type: object
                  description: label selector
                  properties:
                    matchExpressions:
                      type: array
                      items:
                        type: object
                        properties:
                          key:
                            type: string
                          operator:
                            type: string
                          values:
                            type: array
                            items:
                              type: string
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                tolerations:
                  type: array
                  description: toleration
                  items:
                    type: object
                    properties:
                      effect:
                        type: string
                      key:
                        type: string
                      operator:
                        type: string
                      tolerationSeconds:
                        type: integer
                        format: int64
                        minimum: 0
                        maximum: 2147483647
                      value:
                        type: string
            service:
              type: object
              description: "supported service types are ingress and loadBalancer."
              oneOf:
                - required: [ingress]
                - required: [loadBalancer]
              properties:
                ingress:
                  type: object
                  description: "use ingress service type"
                  required: [domainName, port]
                  properties:
                    domainName:
                      type: string
                      description: "(example: 192.168.6.110.nip.io)"
                    port:
                      type: integer
                      description: "external port. Generally use 443 port"
                      minimum: 1
                      maximum: 65535
                loadBalancer:
                  type: object
                  description: "use loadBalancer service type"
                  required: [port]
                  properties:
                    port:
                      type: integer
                      description: "external port. Generally use 443 port"
                      minimum: 1
                      maximum: 65535
            persistentVolumeClaim:
              type: object
              oneOf:
                - required: [exist]
                - required: [create]
              properties:
                mountPath:
                  type: string
                  description: "(default: /var/lib/registry)"
                exist:
                  type: object
                  required: [pvcName]
                  properties:
                    pvcName:
                      type: string
                      description: "Use the pvc you have created."
                create:
                  type: object
                  required: [accessModes, storageSize, storageClassName]
                  properties:
                    accessModes:
                      type: array
                      items:
                        type: string
                        enum: [ReadWriteOnce, ReadWriteMany]
                    storageSize:
                      type: string
                      description: "enter the desired storage size (ex: 10Gi)"
                    storageClassName:
                      type: string
                      description: "enter storage class name available (ex: csi-cephfs-sc)"
                    volumeMode:
                      type: string
                      enum: [Filesystem, Block]
                    deleteWithPvc:
                      type: boolean
                      description: "Delete the pvc as well when this registry is deleted"
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                required: [type]
                properties:
                  lastTransitionTime:
                    type: string
                    format: date-time
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
            phaseChangedAt:
              type: string
            phase:
              type: string
            message:
              type: string
            reason:
              type: string
            capacity:
              type: string
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Image
      type: string
      description: Registry Image
      JSONPath: .spec.image
    - name: Capacity
      type: string
      description: Registry PVC Size
      JSONPath: .status.capacity
    - name: Status
      type: string
      description: Registry Status
      JSONPath: .status.phase
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp