name: cicd
on:
  pull_request:
    types:
      - closed
jobs:
  update_release_draft:
    if: github.base_ref == 'master' && github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}